### PR TITLE
Added Feature1 file by Chaithanya

### PR DESCRIPTION
**Pull request by chaithanya2oct**
Dear Manager,

I have added new feature file named Feature1.feature. Could you please review and let me know any modifications on the same.

Regards,
Chaithanya
SDET

### CODE REVIEW

**Comment by kalamgit143** [comment]
Hi guy...
I studies your fetature file but no browser name in corresponding gherkin senetnce.

**Comment by chaithanya2oct** [comment]
Dear Manager,

Thanks a lot for reviewing my code and as per your review comments I have done the changes. Please Review modified Feature file.
Sorry for the inconvenience.

Regards,
SDET

**Comment by kalamgit143** [comment]
Ok accepted...please go to merge into master

**Comment by kalamgit143** [comment]
Sorry all, please pull whole project once again.

**Pull request merged**
